# Utiliza la imagen oficial de PostgreSQL como base
FROM postgres:16.1

# RUN apt-get update && apt-get -y install libpq-dev gcc && apt-get install -y python3 python3-pip python3-venv

# RUN python3 -m venv /venv
# ENV PATH="/venv/bin:$PATH"

# COPY ./scripts/generate_data.py /docker-entrypoint-initdb.d/
# COPY ./scripts/data /docker-entrypoint-initdb.d/
# COPY ./requirements.txt /docker-entrypoint-initdb.d/
# COPY ./scripts/init_python.sh /docker-entrypoint-initdb.d/

# RUN chmod +x /docker-entrypoint-initdb.d/init_python.sh
# RUN pip install -r /docker-entrypoint-initdb.d/requirements.txt

# ENV POSTGRES_USER=myuser
# ENV POSTGRES_PASSWORD=mypassword
# ENV POSTGRES_DB=mydatabase

EXPOSE 5432
