FROM python:3.9

COPY ./generate_data.py /app/
COPY ./data /app/data/
COPY ./requirements.txt /app/

WORKDIR /app

RUN pip install -r requirements.txt

# CMD ["tail", "-f", "/dev/null"]
CMD ["python", "generate_data.py"]
